# Generated by Django 3.0.2 on 2020-01-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='string',
            field=models.CharField(default='like', max_length=20),
        ),
    ]
