# Generated by Django 3.0.2 on 2020-01-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200126_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='votes_total_dislike',
        ),
        migrations.RemoveField(
            model_name='product',
            name='votes_total_like',
        ),
        migrations.AddField(
            model_name='product',
            name='votes_total',
            field=models.IntegerField(default=1),
        ),
    ]
