# Generated by Django 3.0.2 on 2020-01-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200126_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='string',
        ),
        migrations.AddField(
            model_name='product',
            name='stringlike',
            field=models.CharField(default='dislike', max_length=20),
        ),
    ]
