# Generated by Django 3.0.2 on 2020-01-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200126_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stringlike',
            new_name='string',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stringdislike',
        ),
    ]
