# Generated by Django 3.0.2 on 2020-01-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200126_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='string',
            new_name='stringlike',
        ),
        migrations.AddField(
            model_name='product',
            name='stringdislike',
            field=models.CharField(default='dislike', max_length=20),
        ),
    ]
