# Generated by Django 3.0.2 on 2020-01-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200126_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vote',
            field=models.CharField(default='False', max_length=20),
        ),
    ]
