# Generated by Django 3.0.2 on 2020-01-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='votes_total_dislike',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='votes_total_like',
            field=models.IntegerField(),
        ),
    ]
