# Generated by Django 3.0.2 on 2020-01-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200126_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='votes_total_dislike',
            field=models.IntegerField(default=0),
        ),
    ]
