# Generated by Django 3.0.2 on 2020-01-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200126_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='votes_total_like',
            field=models.IntegerField(default=0),
        ),
    ]
